routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Controllers\DiggingDeeperController;

Auth::routes();

//>> Blog section

Route::get('/', 'Blog\PostController@index');
Route::get('/post/{slug}', 'Blog\PostController@show')->name('post.show');

//<<
//>> Admin section

// Route::get('/', function () {
//     //
// })->middleware('role:admin');

$groupData = [
    'namespace' => 'Blog\Admin',
    'prefix'    => 'admin/blog',
];
Route::group($groupData, function () {
    //BlogCategory
    $methods = ['index', 'edit', 'store', 'update', 'create'];
    Route::resource('categories', 'CategoryController')
        ->only($methods)
        ->names('blog.admin.categories')
        ->middleware('role:admin');

    //BlogPosts
    Route::resource('posts', 'PostController')
        ->except(['show'])
        ->names('blog.admin.posts')
        ->middleware('role:admin');
});

//<<

app/Http/Controllers/Blog/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Blog\Admin;

use App\Http\Controllers\Blog\Admin\BaseController;
use App\Http\Requests\BlogCategoryUpdateRequest;
use App\Http\Requests\BlogCategoryCreateRequest;
use App\Models\BlogCategory;
use App\Repositories\BlogCategoryRepository;
use Illuminate\Support\Str;

class CategoryController extends BaseController
{

    private $blogCategoryRepository;

    public function __construct()
    {
        parent::__construct();
        $this->blogCategoryRepository = app(BlogCategoryRepository::class);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|
     * \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        //$paginator = BlogCategory::paginate(5);

        $paginator = $this->blogCategoryRepository->getAllWithPaginate(5);

        return view('blog.admin.categories.index', compact('paginator'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        $item = new BlogCategory();
        $categoryList = $this->blogCategoryRepository->getForComboBox();

        return view('blog.admin.categories.edit', compact('item', 'categoryList'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(BlogCategoryCreateRequest $request)
    {
        $data = $request->input();

        // in observer

//         if (empty($data['slug'])) {
//             $data['slug'] = Str::slug($data['title']);
// }
        // $item = new BlogCategory($data);
        // $item->save();

        $item = (new BlogCategory())->create($data);

        if ($item) {
            return redirect()->route('blog.admin.categories.edit', [$item->id])
                ->with(['success' => 'Category save']);
        } else {
            return back()->withErrors(array('msg' => 'Save error'))
                ->withInput();
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Contracts\Foundation\Application|
     * \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($id)
    {
        // $item = BlogCategory::findOrFail($id);
        // $categoryList = BlogCategory::all();

        $item = $this->blogCategoryRepository->getEdit($id);

        // $v['title_before'] = $item->title;
        // $item->title = 'Ajkldsdf jfdlskfj 2323';

        // $v['title_after'] = $item->title;
        // $v['getAttribute'] = $item->getAttribute('title');
        // $v['attributesToArray'] = $item->attributesToArray();
        // $v['attributes'] = $item->attributes['title'];
        // $v['getAttributeValue'] = $item->getAttributeValue('title');
        // $v['getMutatedAttributes'] = $item->getMutatedAttributes();
        // $v['hasGetMutator for title'] = $item->hasGetMutator('title');
        // $v['toArray'] = $item->toArray();

        // dd($item, $v);

        $categoryList = $this->blogCategoryRepository->getForCombobox();

        return view('blog.admin.categories.edit', compact('item', 'categoryList'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(BlogCategoryUpdateRequest $request, $id)
    {

        // $rules = [
        //     'title' =>          ['required', 'min:5', 'max:255'],
        //     'slug' =>           ['max:200'],
        //     'description' =>    ['string','max:500','min:3'],
        //     'parent_id' =>      ['required','integer', 'exists:blog_categories,id'],
        // ];

        // $validateData = $this->validate($request, $rules);
        // $validateData = $request->validate($rules);

        $item = $this->blogCategoryRepository->getEdit($id);
        if (empty($item)) {
            return back()
                ->withErrors(['msg' => "No category id=[{$id}]"])
                ->withInput();
        }
        $data = $request->all();
        if (empty($data['slug'])) {
            $data['slug'] = Str::slug($data['title']);
        }
        $result = $item->update($data);
        // $result = $item
        //     ->fill($data)
        //     ->save();

        if ($result) {
            return redirect()
                ->route('blog.admin.categories.edit', $item->id)
                ->with(['success' => 'Save']);
        } else {
            return back()
                ->withErrors(['msg' => 'Error save'])
                ->withInput();
        }
    }
}

resources/views/blog/admin/categories/edit.blade.php
@extends('layouts.app')

@section('content')
@if ($item->exists)
    <form method="POST" action=" {{ route('blog.admin.categories.update', $item->id) }} ">
    @method('PATCH')
@else
    <form method="POST" action=" {{ route('blog.admin.categories.store') }} ">
@endif
@csrf
<div class="container">
    @if ($errors->any())
        <div class="row justify-content-center">
            <div class="col-md-11">
                <div class="alert alert-danger" role="alert">
                    <button type="button" class="close" aria-label="Close" data-dismiss="alert">
                        <span aria-hidden="true">x</span>
                    </button>
                    {{ $errors->first() }}
                </div>
            </div>
        </div>
    @endif
    @if (session('success'))
    <div class="row justify-content-center">
        <div class="col-md-11">
            <div class="alert alert-success" role="alert">
                <button type="button" class="close" aria-label="Close" data-dismiss="alert">
                    <span aria-hidden="true">x</span>
                </button>
                {{ session()->get('success') }}
            </div>
        </div>
    </div>
    @endif
    <div class="row justify-content-center">
        <div class="col-md-8">
            @include('blog.admin.categories.includes.item_edit_main_col')
        </div>
        <div class="col-md-3">
            @include('blog.admin.categories.includes.item_edit_add_col')
        </div>
    </div>
</div>
</form>
@endsection

resources/views/blog/admin/categories/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
            <a class="btn btn-primary" href="{{ route('blog.admin.categories.create') }}">Add category</a>
            </nav>
            <div class="card">
                <div class="card-body">
                    <table class="table table-hover">
                        <thead>
                            <th>#</th>
                            <th>Category</th>
                            <th>Parent</th>
                        </thead>
                        <tbody>
                            @foreach ($paginator as $item)
                                <tr>
                                    <td> {{$item->id}} </td>
                                    <td>
                                        <a href="{{ route('blog.admin.categories.edit', $item->id) }}">
                                        {{ $item->title }}</a>
                                    </td>
                                    <td @if (in_array($item->parent_id, [0, 1])) style="color:#ccc" @endif>
                                       {{-- {{ $item->parentCategory->title ?? '?' }} --}}
                                       {{ $item->ParentTitle }}
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    @if($paginator->total() > $paginator->count())
        <br>
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        {{ $paginator->links( ) }}
                    </div>

                </div>
            </div>
        </div>
    @endif
</div>

@endsection